### ISSUE TITLE
项目1 | 猜数字需求1的问题

### ISSUE THREAD

**Issue by imlinhanchao** [LhengXu/szisa_traning#1]
此处的判断是多余的。能够跳出循环就表示两者相等了。
https://github.com/LhengXu/szisa_traning/blob/2287b82d7f3085254ad9ea54917fff9ab3a48465/03-21-%E7%8C%9C%E6%95%B0%E5%AD%97/Random.java#L31

**Comment by LhengXu** [comment]
已修复
